apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260605-191242-xmczlegex7uv-service
spec:
  selector:
    app: enterprise-system-20260605-191242-xmczlegex7uv
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
